const express = require("express");
const { registerUser, loginUser } = require("../controllers/userControllers");
const app = express();
const auth = require("../middlewares/auth");
const router = new express.Router();
auth();
router.route("/register").post(registerUser);
router.post("/login", loginUser);
// router.get("/chat");
module.exports = router;
